package net.fortytwo.twitlogic.vocabs;

/**
 * User: josh
 * Date: Oct 3, 2009
 * Time: 3:19:13 AM
 */
public interface SIOC {
    public static final String NAMESPACE = "http://rdfs.org/sioc/ns#";

    public static final String
            COMMUNITY = NAMESPACE + "Community",
            CONTAINER = NAMESPACE + "Container",
            FORUM = NAMESPACE + "Forum",
            THREAD = NAMESPACE + "Thread",
            POST = NAMESPACE + "Post",
            ITEM = NAMESPACE + "Item",
            USER = NAMESPACE + "User",
            ROLE = NAMESPACE + "Role",
            SPACE = NAMESPACE + "Space",
            SITE = NAMESPACE + "Site",
            USERGROUP = NAMESPACE + "Usergroup",
            ABOUT = NAMESPACE + "about",
            ACCOUNT_OF = NAMESPACE + "account_of",
            ADMINISTRATOR_OF = NAMESPACE + "administrator_of",
            ATTACHMENT = NAMESPACE + "attachement",
            CONTAINER_OF = NAMESPACE + "container_of",
            CREATOR_OF = NAMESPACE + "creator_of",
            AVATAR = NAMESPACE + "avatar",
            EARLIER_VERSION = NAMESPACE + "earlier_version",
            PREVIOUS_VERSION = NAMESPACE + "previous_version",
            EMAIL = NAMESPACE + "email",
            FOLLOWS = NAMESPACE + "follows",
            FUNCTION_OF = NAMESPACE + "function_of",
            GROUP_OF = NAMESPACE + "group_of",
            HAS_ADMINISTRATOR = NAMESPACE + "has_administrator",
            HAS_CONTAINER = NAMESPACE + "has_container",
            HAS_DISCUSSION = NAMESPACE + "has_discussion",
            HAS_FUNCTION = NAMESPACE + "has_function",
            HAS_GROUP = NAMESPACE + "has_group",
            HAS_HOST = NAMESPACE + "has_host",
            HAS_MEMBER = NAMESPACE + "has_member",
            HAS_MODERATOR = NAMESPACE + "has_moderator",
            HAS_MODIFIER = NAMESPACE + "has_modifier",
            HAS_OWNER = NAMESPACE + "has_owner",
            HAS_PARENT = NAMESPACE + "has_parent",
            HAS_PART = NAMESPACE + "has_part",
            HAS_SCOPE = NAMESPACE + "has_scope",
            HAS_SPACE = NAMESPACE + "has_space",
            HAS_SUBSCRIBER = NAMESPACE + "has_subscriber",
            HAS_USERGROUP = NAMESPACE + "has_usergroup",
            HOLDSACCOUNT = NAMESPACE + "holdsAccount",
            HOST_OF = NAMESPACE + "host_of",
            LATER_VERSION = NAMESPACE + "later_version",
            NEXT_VERSION = NAMESPACE + "next_version",
            MEMBER_OF = NAMESPACE + "member_of",
            MODERATOR_OF = NAMESPACE + "moderator_of",
            MODIFIER_OF = NAMESPACE + "modifier_of",
            NEXT_BY_DATE = NAMESPACE + "next_by_date",
            OWNER_OF = NAMESPACE + "owner_of",
            PARENT_OF = NAMESPACE + "parent_of",
            PART_OF = NAMESPACE + "part_of",
            PREVIOUS_BY_DATE = NAMESPACE + "previous_by_date",
            REFERENCE = NAMESPACE + "reference",
            LINKS_TO = NAMESPACE + "links_to",
            HAS_REPLY = NAMESPACE + "has_reply",
            REPLY_OF = NAMESPACE + "reply_of",
            SCOPE_OF = NAMESPACE + "scope_of",
            SIBLING = NAMESPACE + "sibling",
            SPACE_OF = NAMESPACE + "space_of",
            TOPIC = NAMESPACE + "topic",
            SUBSCRIBER_OF = NAMESPACE + "subscriber_of",
            USERGROUP_OF = NAMESPACE + "usergroup_of",
            CONTENT = NAMESPACE + "content",
            CONTENT_ENCODED = NAMESPACE + "content_encoded",
            CREATED_AT = NAMESPACE + "created_at",
            DECRIPTION = NAMESPACE + "description",
            EMAIL_SHA1 = NAMESPACE + "email_sha1",
            FIRST_NAME = NAMESPACE + "first_name",
            ID = NAMESPACE + "id",
            IP_ADDRESS = NAMESPACE + "ip_address",
            LAST_NAME = NAMESPACE + "last_name",
            MODIFIED_AT = NAMESPACE + "modified_at",
            NAME = NAMESPACE + "name",
            NOTE = NAMESPACE + "note",
            NUM_REPLIES = NAMESPACE + "num_replies",
            NUM_VIEWS = NAMESPACE + "num_views",
            SUBJECT = NAMESPACE + "subject",
            TITLE = NAMESPACE + "title";

    public static final String
            EMBEDSKNOWLEDGE = NAMESPACE + "embedsKnowledge";
}
